### ISSUE TITLE
Backend Data api call assumes all members of model contain all variables

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/climate-explorer#15]
This request:

`http://<CE_BACKEND_URL>/api/data?model=PRISM&emission=historical&time=0&variable=tmax&area=`

Results in:

`Exception: File /home/data/climate/PRISM/dataportal/pr_monClim_PRISM_historical_run1_197101-200012.nc does not have variable tmax.`

The is because the data api call does not filter queried files by the requested variable.

Possible solutions would be to:

1. Filter the [Run list](https://github.com/pacificclimate/climate-explorer/blob/8e4c8b058dae9d81c0daf8a60454b02bad4b05ba/backend/ce/api/data.py#L75) to only produce runs containing files with the requested variable
2. Filter the [getdata request](https://github.com/pacificclimate/climate-explorer/blob/8e4c8b058dae9d81c0daf8a60454b02bad4b05ba/backend/ce/api/data.py#L92) to only be called on files containing the correct variable

**Comment by jameshiebert** [comment]
I vote for option 1. Filtering at the first database query is the right thing to do.

**Comment by basilveerman** [comment]
I think we need to actually do both. Filtering on the Run query will eliminate runs which do not contain any file representing a variable, but there could still be data_files in that Run which do not contain the requested variable.

[This fix](http://hastebin.com/dumohedura) seems to produce the correct result. Just writing tests for it now.

**Comment by jameshiebert** [comment]
I think you need a `pep8` check on line 29 :)
